// Web-only mock data for local UI verification
// These IDs match what initDatabase() would seed on native

const NOW = '2025-01-01T00:00:00.000Z';

export const MOCK_CATEGORIES = [
  { id: 'cat-default-0',  name: '上衣',  color: '#f48fb1', sort_order: 0,  is_default: 1, created_at: NOW },
  { id: 'cat-default-1',  name: '裙裝',  color: '#ce93d8', sort_order: 1,  is_default: 1, created_at: NOW },
  { id: 'cat-default-2',  name: '褲裝',  color: '#90caf9', sort_order: 2,  is_default: 1, created_at: NOW },
  { id: 'cat-default-3',  name: '洋裝',  color: '#f48fb1', sort_order: 3,  is_default: 1, created_at: NOW },
  { id: 'cat-default-4',  name: '外套',  color: '#a5d6a7', sort_order: 4,  is_default: 1, created_at: NOW },
  { id: 'cat-default-5',  name: '套裝',  color: '#80cbc4', sort_order: 5,  is_default: 1, created_at: NOW },
  { id: 'cat-default-6',  name: '日常',  color: '#ffe082', sort_order: 6,  is_default: 1, created_at: NOW },
  { id: 'cat-default-7',  name: '鞋類',  color: '#bcaaa4', sort_order: 7,  is_default: 1, created_at: NOW },
  { id: 'cat-default-8',  name: '包包',  color: '#ef9a9a', sort_order: 8,  is_default: 1, created_at: NOW },
  { id: 'cat-default-9',  name: '猶豫',  color: '#b0bec5', sort_order: 9,  is_default: 1, created_at: NOW },
  { id: 'cat-default-10', name: '留校',  color: '#c5cae9', sort_order: 10, is_default: 1, created_at: NOW },
  { id: 'cat-default-11', name: '冷凍',  color: '#b3e5fc', sort_order: 11, is_default: 1, created_at: NOW },
  { id: 'cat-default-12', name: '未分類', color: '#e0e0e0', sort_order: 12, is_default: 1, created_at: NOW },
];

export const MOCK_ORIGINS = [
  { id: 'origin-default-0', name: '日貨',   is_default: 1, deleted: 0, created_at: NOW },
  { id: 'origin-default-1', name: '韓貨',   is_default: 1, deleted: 0, created_at: NOW },
  { id: 'origin-default-2', name: '品牌',   is_default: 1, deleted: 0, created_at: NOW },
  { id: 'origin-default-3', name: '蝦皮',   is_default: 1, deleted: 0, created_at: NOW },
  { id: 'origin-default-4', name: '其他',   is_default: 1, deleted: 0, created_at: NOW },
];

export const MOCK_COLORS = [
  { id: 'color-default-0',  name: '黑色',  is_default: 1, created_at: NOW },
  { id: 'color-default-1',  name: '白色',  is_default: 1, created_at: NOW },
  { id: 'color-default-2',  name: '灰色',  is_default: 1, created_at: NOW },
  { id: 'color-default-3',  name: '紅色',  is_default: 1, created_at: NOW },
  { id: 'color-default-4',  name: '杏色',  is_default: 1, created_at: NOW },
  { id: 'color-default-5',  name: '卡其色', is_default: 1, created_at: NOW },
  { id: 'color-default-6',  name: '咖啡色', is_default: 1, created_at: NOW },
  { id: 'color-default-7',  name: '綠色',  is_default: 1, created_at: NOW },
  { id: 'color-default-8',  name: '粉色',  is_default: 1, created_at: NOW },
  { id: 'color-default-9',  name: '紫色',  is_default: 1, created_at: NOW },
  { id: 'color-default-10', name: '黃色',  is_default: 1, created_at: NOW },
  { id: 'color-default-11', name: '藍色',  is_default: 1, created_at: NOW },
  { id: 'color-default-12', name: '格紋',  is_default: 1, created_at: NOW },
  { id: 'color-default-13', name: '條紋',  is_default: 1, created_at: NOW },
  { id: 'color-default-14', name: '點點',  is_default: 1, created_at: NOW },
];

export const MOCK_ITEMS = [
  {
    id: 'mock-item-1', brand: 'UNIQLO', name: '白色棉質T恤',
    purchase_date: '2024-03-01', purchase_time: null,
    category_id: 'cat-default-0', origin_id: 'origin-default-2',
    color_ids: '["color-default-1"]', grade: 'A',
    original_price: 490, special_price: null, discount_price: null,
    size: 'M', weight: null, body_type: null, suggested_weight: null,
    usage_count: 8, seasons: '["春","夏"]',
    mini_note: '好搭配的基本款', pros: '透氣舒適、好洗', cons: null, remark: null,
    photo_ids: '[]', created_at: '2024-03-01T10:00:00.000Z', updated_at: '2024-03-01T10:00:00.000Z', deleted_at: null,
  },
  {
    id: 'mock-item-2', brand: 'ZARA', name: '格紋西裝外套',
    purchase_date: '2024-02-14', purchase_time: null,
    category_id: 'cat-default-4', origin_id: 'origin-default-2',
    color_ids: '["color-default-12"]', grade: 'A',
    original_price: 3990, special_price: 2490, discount_price: null,
    size: 'S', weight: null, body_type: null, suggested_weight: null,
    usage_count: 3, seasons: '["秋","冬"]',
    mini_note: null, pros: '版型俐落', cons: '稍微厚重', remark: null,
    photo_ids: '[]', created_at: '2024-02-14T10:00:00.000Z', updated_at: '2024-02-14T10:00:00.000Z', deleted_at: null,
  },
  {
    id: 'mock-item-3', brand: "LEVI'S", name: '直筒牛仔褲',
    purchase_date: '2023-11-11', purchase_time: null,
    category_id: 'cat-default-2', origin_id: 'origin-default-2',
    color_ids: '["color-default-11"]', grade: 'A',
    original_price: 2990, special_price: 1890, discount_price: null,
    size: '27', weight: null, body_type: null, suggested_weight: null,
    usage_count: 15, seasons: '["春","秋","冬"]',
    mini_note: '百搭款必備', pros: '耐穿、好搭', cons: null, remark: null,
    photo_ids: '[]', created_at: '2023-11-11T10:00:00.000Z', updated_at: '2023-11-11T10:00:00.000Z', deleted_at: null,
  },
  {
    id: 'mock-item-4', brand: 'H&M', name: '碎花洋裝',
    purchase_date: '2024-04-20', purchase_time: null,
    category_id: 'cat-default-3', origin_id: 'origin-default-2',
    color_ids: '["color-default-8"]', grade: 'B',
    original_price: 990, special_price: 790, discount_price: null,
    size: 'S', weight: null, body_type: null, suggested_weight: null,
    usage_count: 4, seasons: '["春","夏"]',
    mini_note: null, pros: '輕盈透氣', cons: '容易皺', remark: null,
    photo_ids: '[]', created_at: '2024-04-20T10:00:00.000Z', updated_at: '2024-04-20T10:00:00.000Z', deleted_at: null,
  },
  {
    id: 'mock-item-5', brand: 'MUJI', name: '米色卡其褲',
    purchase_date: '2024-01-10', purchase_time: null,
    category_id: 'cat-default-2', origin_id: 'origin-default-0',
    color_ids: '["color-default-5"]', grade: 'A',
    original_price: 1490, special_price: null, discount_price: null,
    size: 'M', weight: null, body_type: null, suggested_weight: null,
    usage_count: 10, seasons: '["春","秋"]',
    mini_note: '工作日常必備', pros: '舒適有型', cons: null, remark: null,
    photo_ids: '[]', created_at: '2024-01-10T10:00:00.000Z', updated_at: '2024-01-10T10:00:00.000Z', deleted_at: null,
  },
  {
    id: 'mock-item-6', brand: 'Nike', name: 'Air Force 1',
    purchase_date: '2023-09-15', purchase_time: null,
    category_id: 'cat-default-7', origin_id: 'origin-default-2',
    color_ids: '["color-default-1"]', grade: 'A',
    original_price: 3200, special_price: null, discount_price: null,
    size: '23.5', weight: null, body_type: null, suggested_weight: null,
    usage_count: 20, seasons: '["春","夏","秋","冬"]',
    mini_note: '全年最常穿的鞋', pros: '百搭、耐穿', cons: '白色難保養', remark: null,
    photo_ids: '[]', created_at: '2023-09-15T10:00:00.000Z', updated_at: '2023-09-15T10:00:00.000Z', deleted_at: null,
  },
  {
    id: 'mock-item-7', brand: 'COACH', name: '托特包',
    purchase_date: '2023-06-06', purchase_time: null,
    category_id: 'cat-default-8', origin_id: 'origin-default-2',
    color_ids: '["color-default-6"]', grade: 'A',
    original_price: 15000, special_price: 12000, discount_price: null,
    size: null, weight: null, body_type: null, suggested_weight: null,
    usage_count: 25, seasons: '["春","夏","秋","冬"]',
    mini_note: '上班包，天天用', pros: '容量大、耐用', cons: '稍重', remark: null,
    photo_ids: '[]', created_at: '2023-06-06T10:00:00.000Z', updated_at: '2023-06-06T10:00:00.000Z', deleted_at: null,
  },
  {
    id: 'mock-item-8', brand: 'GU', name: '黑色針織毛衣',
    purchase_date: '2023-10-01', purchase_time: null,
    category_id: 'cat-default-0', origin_id: 'origin-default-0',
    color_ids: '["color-default-0"]', grade: 'B',
    original_price: 790, special_price: null, discount_price: null,
    size: 'M', weight: null, body_type: null, suggested_weight: null,
    usage_count: 6, seasons: '["秋","冬"]',
    mini_note: null, pros: '保暖', cons: '起毛球', remark: null,
    photo_ids: '[]', created_at: '2023-10-01T10:00:00.000Z', updated_at: '2023-10-01T10:00:00.000Z', deleted_at: null,
  },
  {
    id: 'mock-item-9', brand: 'QUEEN SHOP', name: '百褶短裙',
    purchase_date: '2024-05-18', purchase_time: null,
    category_id: 'cat-default-1', origin_id: 'origin-default-3',
    color_ids: '["color-default-4"]', grade: 'A',
    original_price: 680, special_price: null, discount_price: null,
    size: 'S', weight: null, body_type: null, suggested_weight: null,
    usage_count: 5, seasons: '["春","夏"]',
    mini_note: null, pros: '顯腿長', cons: null, remark: null,
    photo_ids: '[]', created_at: '2024-05-18T10:00:00.000Z', updated_at: '2024-05-18T10:00:00.000Z', deleted_at: null,
  },
  {
    id: 'mock-item-10', brand: null, name: '駝色大衣',
    purchase_date: '2022-12-01', purchase_time: null,
    category_id: 'cat-default-4', origin_id: 'origin-default-1',
    color_ids: '["color-default-6"]', grade: 'A',
    original_price: 4500, special_price: null, discount_price: null,
    size: 'M', weight: null, body_type: null, suggested_weight: null,
    usage_count: 12, seasons: '["冬"]',
    mini_note: '韓國帶回來的', pros: '超保暖、顯高', cons: '乾洗費貴', remark: null,
    photo_ids: '[]', created_at: '2022-12-01T10:00:00.000Z', updated_at: '2022-12-01T10:00:00.000Z', deleted_at: null,
  },
  {
    id: 'mock-item-11', brand: 'LAKOLE', name: '緞面微光澤點點長裙',
    purchase_date: '2024-06-10', purchase_time: null,
    category_id: 'cat-default-1', origin_id: 'origin-default-3',
    color_ids: '["color-default-0"]', grade: 'A',
    original_price: 1290, special_price: null, discount_price: null,
    size: 'M', weight: null, body_type: null, suggested_weight: null,
    usage_count: 2, seasons: '["夏","秋"]',
    mini_note: null, pros: '有質感', cons: null, remark: null,
    photo_ids: '[]', created_at: '2024-06-10T10:00:00.000Z', updated_at: '2024-06-10T10:00:00.000Z', deleted_at: null,
  },
  {
    id: 'mock-item-12', brand: 'UNIQLO', name: '奇蹟空氣感西裝外套',
    purchase_date: '2024-03-20', purchase_time: null,
    category_id: 'cat-default-4', origin_id: 'origin-default-2',
    color_ids: '["color-default-2"]', grade: 'A',
    original_price: 2490, special_price: null, discount_price: null,
    size: 'M', weight: null, body_type: null, suggested_weight: null,
    usage_count: 7, seasons: '["春","秋"]',
    mini_note: '辦公室穿搭必備', pros: '輕薄好攜帶', cons: null, remark: null,
    photo_ids: '[]', created_at: '2024-03-20T10:00:00.000Z', updated_at: '2024-03-20T10:00:00.000Z', deleted_at: null,
  },
  {
    id: 'mock-item-13', brand: 'New Balance', name: '574 運動鞋',
    purchase_date: '2024-07-01', purchase_time: null,
    category_id: 'cat-default-7', origin_id: 'origin-default-2',
    color_ids: '["color-default-7","color-default-1"]', grade: 'A',
    original_price: 2800, special_price: null, discount_price: null,
    size: '23.5', weight: null, body_type: null, suggested_weight: null,
    usage_count: 9, seasons: '["春","夏","秋"]',
    mini_note: null, pros: '超級舒適', cons: null, remark: null,
    photo_ids: '[]', created_at: '2024-07-01T10:00:00.000Z', updated_at: '2024-07-01T10:00:00.000Z', deleted_at: null,
  },
  {
    id: 'mock-item-14', brand: 'COS', name: '寬版亞麻上衣',
    purchase_date: '2024-08-15', purchase_time: null,
    category_id: 'cat-default-0', origin_id: 'origin-default-2',
    color_ids: '["color-default-4"]', grade: 'A',
    original_price: 1890, special_price: null, discount_price: null,
    size: 'XS', weight: null, body_type: null, suggested_weight: null,
    usage_count: 6, seasons: '["夏"]',
    mini_note: '夏天神器', pros: '超涼爽', cons: null, remark: null,
    photo_ids: '[]', created_at: '2024-08-15T10:00:00.000Z', updated_at: '2024-08-15T10:00:00.000Z', deleted_at: null,
  },
  {
    id: 'mock-item-15', brand: 'QUEEN SHOP', name: '開衩皮革短褲裙',
    purchase_date: '2024-09-01', purchase_time: null,
    category_id: 'cat-default-1', origin_id: 'origin-default-3',
    color_ids: '["color-default-0"]', grade: 'B',
    original_price: 880, special_price: null, discount_price: null,
    size: 'S', weight: null, body_type: null, suggested_weight: null,
    usage_count: 1, seasons: '["秋"]',
    mini_note: '冷凍觀察中', pros: null, cons: '不確定好不好搭', remark: null,
    photo_ids: '[]', created_at: '2024-09-01T10:00:00.000Z', updated_at: '2024-09-01T10:00:00.000Z', deleted_at: null,
  },
];

export const MOCK_OUTFITS = [
  {
    id: 'mock-outfit-1',
    date: '2025-04-15', time: '09:00',
    weather: '晴天', temperature: '22°C',
    county: '台北市', place: '辦公室',
    note: '上班通勤 look，簡單俐落',
    photo_ids: '[]',
    item_ids: '["mock-item-1","mock-item-5","mock-item-6"]',
    created_at: '2025-04-15T09:00:00.000Z', updated_at: '2025-04-15T09:00:00.000Z',
  },
  {
    id: 'mock-outfit-2',
    date: '2025-04-20', time: '14:00',
    weather: '多雲', temperature: '18°C',
    county: '台北市', place: '信義區',
    note: '週末購物，輕鬆休閒',
    photo_ids: '[]',
    item_ids: '["mock-item-4","mock-item-7","mock-item-13"]',
    created_at: '2025-04-20T14:00:00.000Z', updated_at: '2025-04-20T14:00:00.000Z',
  },
  {
    id: 'mock-outfit-3',
    date: '2025-03-08', time: null,
    weather: '陰天', temperature: '15°C',
    county: '新北市', place: '淡水老街',
    note: '週末踏青',
    photo_ids: '[]',
    item_ids: '["mock-item-8","mock-item-3","mock-item-6"]',
    created_at: '2025-03-08T10:00:00.000Z', updated_at: '2025-03-08T10:00:00.000Z',
  },
  {
    id: 'mock-outfit-4',
    date: '2025-02-14', time: '19:00',
    weather: '晴天', temperature: '14°C',
    county: '台北市', place: '大安區餐廳',
    note: '情人節約會，特別打扮',
    photo_ids: '[]',
    item_ids: '["mock-item-9","mock-item-2","mock-item-7"]',
    created_at: '2025-02-14T19:00:00.000Z', updated_at: '2025-02-14T19:00:00.000Z',
  },
  {
    id: 'mock-outfit-5',
    date: '2025-01-15', time: null,
    weather: '晴天', temperature: '8°C',
    county: '台北市', place: null,
    note: null,
    photo_ids: '[]',
    item_ids: '["mock-item-10","mock-item-5","mock-item-6"]',
    created_at: '2025-01-15T10:00:00.000Z', updated_at: '2025-01-15T10:00:00.000Z',
  },
];

export const MOCK_VOTE_COUNTS = [
  { item_id: 'mock-item-6',  count: 5 },
  { item_id: 'mock-item-7',  count: 8 },
  { item_id: 'mock-item-3',  count: 3 },
  { item_id: 'mock-item-1',  count: 2 },
  { item_id: 'mock-item-10', count: 4 },
];
